name: build

on:
  push:
    branches:
      - main

jobs:
  build_package:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      version: '1.1.15'
      latest: true
      major_only_tag: true
      revision: '2'
    secrets: inherit
